name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Build project
        run: ndk-build

      - name: Rename build artifacts
        run: |
          mv libs/arm64-v8a/Injector libs/arm64-v8a/injector-arm64-v8a
          mv libs/armeabi-v7a/Injector libs/armeabi-v7a/injector-armeabi-v7a
          mv libs/x86/Injector libs/x86/injector-x86
          mv libs/x86_64/Injector libs/x86_64/injector-x86_64

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libs/*/injector-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Automated release for ${{ github.ref_name }}"
